name: pix_glance
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
  file_picker: ^8.1.2
  open_file: ^3.5.6
  photo_view: ^0.15.0
  flutter_svg: ^2.0.10+1
  image: ^4.2.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  heic_to_jpg: ^0.2.0
  fullscreen_window: ^1.1.0
  receive_sharing_intent: ^1.5.3
  flutter_window_close: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
